### ISSUE TITLE
Contribute: write tests

### ISSUE THREAD

**Issue by meysam81** [mavenium/PyQuotes#3]
Hello,

I'd like to announce my enthusiasm for contributing to this repository. I like django & I'm well experienced with testing. This issue is just for me to say hi; you'll hear from me soon enough.

**Comment by mavenium** [comment]
Hi
I was glad to read this issue and I would appreciate you for doing this issue.
Good luck ;)

**Comment by meysam81** [comment]
> Hi
> I was glad to read this issue and I would appreciate you for doing this issue.
> Good luck ;)

My pleasure :clinking_glasses:
